version: "3.7"
services:
  container-app:
    container_name: stablefast-app
    image: stablefast-app:v1
    build:
      context: .
      dockerfile: ./Dockerfile_gpu
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    #Directly attach working dir to container
    #volumes:
    #  - ./app:/code/
    
    restart: unless-stopped
    #env_file: .env
    
    # environment variables from .env file
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      UVICORN_PORT: ${UVICORN_PORT}
      NUMBER_WORKERS: ${NUMBER_WORKERS}
